security:
    # Password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Form login configuration
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\CustomAuthenticationSuccessHandler
                enable_csrf: true

            # Remember me functionality
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds

            # Logout configuration
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_default

    # Access control configuration (Move this out of firewalls)
    access_control:
        # Access for clients
        - { path: ^/reclamation, allow_if: 'is_granted("IS_CLIENT")' }

        # Access for team leaders
        - { path: ^/chef_equipe, allow_if: 'is_granted("IS_CHEF_EQUIPE")' }

        # Access for technicians
        - { path: ^/technicien, allow_if: 'is_granted("IS_TECHNICIAN")' }

when@test:
    security:
        password_hashers:
            # Reduce the security hashing costs for testing
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
