# config/services.yaml

services:
    # Default configuration for services
    _defaults:
        autowire: true      # Automatically inject dependencies
        autoconfigure: true # Automatically register services as commands, event subscribers, etc.
        public: false       # Services are private by default

    App\Security\CustomAuthenticationSuccessHandler:
        arguments:
            $router: '@router'
            $authorizationChecker: '@security.authorization_checker'
        tags:
            - { name: 'security.authentication_success_handler' }

    # Explicitly register the security voter
    App\Security\UserTypeVoter:
        tags: ['security.voter'] # Registers the voter service

    # Load other services in the App namespace
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
